package com.example.computershopmobile.proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Client.proto

public final class Client {
  private Client() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CreateUserRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreateUserRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string login = 1;</code>
     * @return The login.
     */
    String getLogin();
    /**
     * <code>string login = 1;</code>
     * @return The bytes for login.
     */
    com.google.protobuf.ByteString
        getLoginBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string lastname = 4;</code>
     * @return The lastname.
     */
    String getLastname();
    /**
     * <code>string lastname = 4;</code>
     * @return The bytes for lastname.
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>string surname = 5;</code>
     * @return The surname.
     */
    String getSurname();
    /**
     * <code>string surname = 5;</code>
     * @return The bytes for surname.
     */
    com.google.protobuf.ByteString
        getSurnameBytes();

    /**
     * <code>string email = 6;</code>
     * @return The email.
     */
    String getEmail();
    /**
     * <code>string email = 6;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>bytes avatar = 7;</code>
     * @return The avatar.
     */
    com.google.protobuf.ByteString getAvatar();
  }
  /**
   * Protobuf type {@code CreateUserRequest}
   */
  public  static final class CreateUserRequest extends
      com.google.protobuf.GeneratedMessageLite<
          CreateUserRequest, CreateUserRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:CreateUserRequest)
      CreateUserRequestOrBuilder {
    private CreateUserRequest() {
      login_ = "";
      password_ = "";
      name_ = "";
      lastname_ = "";
      surname_ = "";
      email_ = "";
      avatar_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int LOGIN_FIELD_NUMBER = 1;
    private String login_;
    /**
     * <code>string login = 1;</code>
     * @return The login.
     */
    @Override
    public String getLogin() {
      return login_;
    }
    /**
     * <code>string login = 1;</code>
     * @return The bytes for login.
     */
    @Override
    public com.google.protobuf.ByteString
        getLoginBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(login_);
    }
    /**
     * <code>string login = 1;</code>
     * @param value The login to set.
     */
    private void setLogin(
        String value) {
      Class<?> valueClass = value.getClass();
  
      login_ = value;
    }
    /**
     * <code>string login = 1;</code>
     */
    private void clearLogin() {
      
      login_ = getDefaultInstance().getLogin();
    }
    /**
     * <code>string login = 1;</code>
     * @param value The bytes for login to set.
     */
    private void setLoginBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      login_ = value.toStringUtf8();
      
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private String password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @Override
    public String getPassword() {
      return password_;
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>string password = 2;</code>
     * @param value The password to set.
     */
    private void setPassword(
        String value) {
      Class<?> valueClass = value.getClass();
  
      password_ = value;
    }
    /**
     * <code>string password = 2;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      password_ = value.toStringUtf8();
      
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private String name_;
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      return name_;
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 3;</code>
     * @param value The name to set.
     */
    private void setName(
        String value) {
      Class<?> valueClass = value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 3;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int LASTNAME_FIELD_NUMBER = 4;
    private String lastname_;
    /**
     * <code>string lastname = 4;</code>
     * @return The lastname.
     */
    @Override
    public String getLastname() {
      return lastname_;
    }
    /**
     * <code>string lastname = 4;</code>
     * @return The bytes for lastname.
     */
    @Override
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(lastname_);
    }
    /**
     * <code>string lastname = 4;</code>
     * @param value The lastname to set.
     */
    private void setLastname(
        String value) {
      Class<?> valueClass = value.getClass();
  
      lastname_ = value;
    }
    /**
     * <code>string lastname = 4;</code>
     */
    private void clearLastname() {
      
      lastname_ = getDefaultInstance().getLastname();
    }
    /**
     * <code>string lastname = 4;</code>
     * @param value The bytes for lastname to set.
     */
    private void setLastnameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      lastname_ = value.toStringUtf8();
      
    }

    public static final int SURNAME_FIELD_NUMBER = 5;
    private String surname_;
    /**
     * <code>string surname = 5;</code>
     * @return The surname.
     */
    @Override
    public String getSurname() {
      return surname_;
    }
    /**
     * <code>string surname = 5;</code>
     * @return The bytes for surname.
     */
    @Override
    public com.google.protobuf.ByteString
        getSurnameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(surname_);
    }
    /**
     * <code>string surname = 5;</code>
     * @param value The surname to set.
     */
    private void setSurname(
        String value) {
      Class<?> valueClass = value.getClass();
  
      surname_ = value;
    }
    /**
     * <code>string surname = 5;</code>
     */
    private void clearSurname() {
      
      surname_ = getDefaultInstance().getSurname();
    }
    /**
     * <code>string surname = 5;</code>
     * @param value The bytes for surname to set.
     */
    private void setSurnameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      surname_ = value.toStringUtf8();
      
    }

    public static final int EMAIL_FIELD_NUMBER = 6;
    private String email_;
    /**
     * <code>string email = 6;</code>
     * @return The email.
     */
    @Override
    public String getEmail() {
      return email_;
    }
    /**
     * <code>string email = 6;</code>
     * @return The bytes for email.
     */
    @Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(email_);
    }
    /**
     * <code>string email = 6;</code>
     * @param value The email to set.
     */
    private void setEmail(
        String value) {
      Class<?> valueClass = value.getClass();
  
      email_ = value;
    }
    /**
     * <code>string email = 6;</code>
     */
    private void clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
    }
    /**
     * <code>string email = 6;</code>
     * @param value The bytes for email to set.
     */
    private void setEmailBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      email_ = value.toStringUtf8();
      
    }

    public static final int AVATAR_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString avatar_;
    /**
     * <code>bytes avatar = 7;</code>
     * @return The avatar.
     */
    @Override
    public com.google.protobuf.ByteString getAvatar() {
      return avatar_;
    }
    /**
     * <code>bytes avatar = 7;</code>
     * @param value The avatar to set.
     */
    private void setAvatar(com.google.protobuf.ByteString value) {
      Class<?> valueClass = value.getClass();
  
      avatar_ = value;
    }
    /**
     * <code>bytes avatar = 7;</code>
     */
    private void clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
    }

    public static CreateUserRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CreateUserRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CreateUserRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CreateUserRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CreateUserRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CreateUserRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CreateUserRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CreateUserRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CreateUserRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CreateUserRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CreateUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CreateUserRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(CreateUserRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code CreateUserRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CreateUserRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:CreateUserRequest)
        CreateUserRequestOrBuilder {
      // Construct using Client.CreateUserRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string login = 1;</code>
       * @return The login.
       */
      @Override
      public String getLogin() {
        return instance.getLogin();
      }
      /**
       * <code>string login = 1;</code>
       * @return The bytes for login.
       */
      @Override
      public com.google.protobuf.ByteString
          getLoginBytes() {
        return instance.getLoginBytes();
      }
      /**
       * <code>string login = 1;</code>
       * @param value The login to set.
       * @return This builder for chaining.
       */
      public Builder setLogin(
          String value) {
        copyOnWrite();
        instance.setLogin(value);
        return this;
      }
      /**
       * <code>string login = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogin() {
        copyOnWrite();
        instance.clearLogin();
        return this;
      }
      /**
       * <code>string login = 1;</code>
       * @param value The bytes for login to set.
       * @return This builder for chaining.
       */
      public Builder setLoginBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLoginBytes(value);
        return this;
      }

      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      @Override
      public String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      @Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      @Override
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      @Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>string lastname = 4;</code>
       * @return The lastname.
       */
      @Override
      public String getLastname() {
        return instance.getLastname();
      }
      /**
       * <code>string lastname = 4;</code>
       * @return The bytes for lastname.
       */
      @Override
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        return instance.getLastnameBytes();
      }
      /**
       * <code>string lastname = 4;</code>
       * @param value The lastname to set.
       * @return This builder for chaining.
       */
      public Builder setLastname(
          String value) {
        copyOnWrite();
        instance.setLastname(value);
        return this;
      }
      /**
       * <code>string lastname = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastname() {
        copyOnWrite();
        instance.clearLastname();
        return this;
      }
      /**
       * <code>string lastname = 4;</code>
       * @param value The bytes for lastname to set.
       * @return This builder for chaining.
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLastnameBytes(value);
        return this;
      }

      /**
       * <code>string surname = 5;</code>
       * @return The surname.
       */
      @Override
      public String getSurname() {
        return instance.getSurname();
      }
      /**
       * <code>string surname = 5;</code>
       * @return The bytes for surname.
       */
      @Override
      public com.google.protobuf.ByteString
          getSurnameBytes() {
        return instance.getSurnameBytes();
      }
      /**
       * <code>string surname = 5;</code>
       * @param value The surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurname(
          String value) {
        copyOnWrite();
        instance.setSurname(value);
        return this;
      }
      /**
       * <code>string surname = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSurname() {
        copyOnWrite();
        instance.clearSurname();
        return this;
      }
      /**
       * <code>string surname = 5;</code>
       * @param value The bytes for surname to set.
       * @return This builder for chaining.
       */
      public Builder setSurnameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSurnameBytes(value);
        return this;
      }

      /**
       * <code>string email = 6;</code>
       * @return The email.
       */
      @Override
      public String getEmail() {
        return instance.getEmail();
      }
      /**
       * <code>string email = 6;</code>
       * @return The bytes for email.
       */
      @Override
      public com.google.protobuf.ByteString
          getEmailBytes() {
        return instance.getEmailBytes();
      }
      /**
       * <code>string email = 6;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          String value) {
        copyOnWrite();
        instance.setEmail(value);
        return this;
      }
      /**
       * <code>string email = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        copyOnWrite();
        instance.clearEmail();
        return this;
      }
      /**
       * <code>string email = 6;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailBytes(value);
        return this;
      }

      /**
       * <code>bytes avatar = 7;</code>
       * @return The avatar.
       */
      @Override
      public com.google.protobuf.ByteString getAvatar() {
        return instance.getAvatar();
      }
      /**
       * <code>bytes avatar = 7;</code>
       * @param value The avatar to set.
       * @return This builder for chaining.
       */
      public Builder setAvatar(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAvatar(value);
        return this;
      }
      /**
       * <code>bytes avatar = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvatar() {
        copyOnWrite();
        instance.clearAvatar();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CreateUserRequest)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CreateUserRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "login_",
              "password_",
              "name_",
              "lastname_",
              "surname_",
              "email_",
              "avatar_",
            };
            String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0208\u0007\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<CreateUserRequest> parser = PARSER;
          if (parser == null) {
            synchronized (CreateUserRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<CreateUserRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CreateUserRequest)
    private static final CreateUserRequest DEFAULT_INSTANCE;
    static {
      CreateUserRequest defaultInstance = new CreateUserRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CreateUserRequest.class, defaultInstance);
    }

    public static CreateUserRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CreateUserRequest> PARSER;

    public static com.google.protobuf.Parser<CreateUserRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CreateUserResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreateUserResponse)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code CreateUserResponse}
   */
  public  static final class CreateUserResponse extends
      com.google.protobuf.GeneratedMessageLite<
          CreateUserResponse, CreateUserResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:CreateUserResponse)
      CreateUserResponseOrBuilder {
    private CreateUserResponse() {
    }
    public static CreateUserResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CreateUserResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CreateUserResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CreateUserResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CreateUserResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CreateUserResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CreateUserResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CreateUserResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CreateUserResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CreateUserResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CreateUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CreateUserResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(CreateUserResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code CreateUserResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CreateUserResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:CreateUserResponse)
        CreateUserResponseOrBuilder {
      // Construct using Client.CreateUserResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:CreateUserResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CreateUserResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = null;
            String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<CreateUserResponse> parser = PARSER;
          if (parser == null) {
            synchronized (CreateUserResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<CreateUserResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CreateUserResponse)
    private static final CreateUserResponse DEFAULT_INSTANCE;
    static {
      CreateUserResponse defaultInstance = new CreateUserResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CreateUserResponse.class, defaultInstance);
    }

    public static CreateUserResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CreateUserResponse> PARSER;

    public static com.google.protobuf.Parser<CreateUserResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
